import { Content, ContentData } from 'sunbird-sdk';

const contentDate: ContentData = {
    'identifier': '',
    'name': '',
    'appIcon': '',
    'description': '',
    'pkgVersion': '',
    'status': '',
    'size': '',
    'owner': '',
    'creator': '',
    'subject': '',
    'board': '',
    'medium': '',
    'publisher': '',
    'me_totalRatings': '',
    'me_averageRating': '',
    'me_totalDownloads': '',
    'copyright': '',
    'license': '',
    'expires': '',
    'downloadUrl': '',
    'variants': {},
    'artifactUrl': '',
    'language': [],
    'gradeLevel': [],
    'osId': '',
    'contentType': '',
    'resourceType': '',
    'mimeType': '',
    'artifactMimeType': '',
    'versionKey': '',
    'contentEncoding': '',
    'contentDisposition': '',
    'contentTypesCount': '',
    'lastPublishedOn': '',
    'createdOn': '',
    'createdBy': '',
    'channel': '',
    'screenshots': [],
    'audience': '',
    'pragma': [],
    'attributions': [],
    'dialcodes': [],
    'childNodes': [],
    'previewUrl': '',
    'framework': '',
    'creators': '',
    'contributors': '',
    'streamingUrl': '',
    'totalScore': '',
}

export const downloadedContentsMock: Content[] = [
    {
      'identifier': 'do_2127241220330455041285',
      'contentData': contentDate,
      'isUpdateAvailable': false,
      'mimeType': 'application/vnd.ekstep.ecml-archive',
      'basePath': '/storage/emulated/0/Android/data/org.sunbird.app.staging/files/content/do_2127241220330455041285/',
      'contentType': 'resource',
      'isAvailableLocally': true,
      'referenceCount': 1,
      'sizeOnDevice': 276128,
      'lastUsedTime': 1555070969699,
      'lastUpdatedTime': 1558008543000
    }
]