
export const mockRes = {
  filterCriteria:
  {'age': 0, 'contentTypes': ['Story', 'Worksheet', 'Game', 'Resource', 'Collection', 'TextBook', 'LessonPlan'],
  'facetFilters': [{'name': 'board', 'values': [{'apply': false, 'count': 103, 'name': 'cbse'},
  {'apply': true, 'count': 6, 'name': 'icse'}, {'apply': false, 'count': 59, 'name': 'ncert'},
  {'apply': false, 'count': 4, 'name': 'state (andhra pradesh)'}, {'apply': false, 'count': 8, 'name': 'state (maharashtra)'},
  {'apply': false, 'count': 4, 'name': 'state (rajasthan)'}, {'apply': false, 'count': 4, 'name': 'state (tamil nadu)'},
  {'apply': false, 'count': 28, 'name': 'state (uttar pradesh)'}, {'apply': false, 'count': 3, 'name': 'other'}],
  'translatedName': 'Board'}, {'name': 'gradeLevel', 'values': [{'apply': false, 'count': 7, 'name': 'class 10'},
  {'apply': false, 'count': 174, 'name': 'class 1'}, {'apply': false, 'count': 73, 'name': 'class 3'},
  {'apply': false, 'count': 87, 'name': 'class 2'}, {'apply': false, 'count': 65, 'name': 'class 5'},
  {'apply': false, 'count': 7, 'name': 'class 11'}, {'apply': false, 'count': 73, 'name': 'class 4'},
  {'apply': false, 'count': 4, 'name': 'class 12'}, {'apply': false, 'count': 26, 'name': 'class 7'},
  {'apply': false, 'count': 15, 'name': 'class 6'}, {'apply': false, 'count': 9, 'name': 'class 9'},
  {'apply': false, 'count': 4, 'name': 'class 8'}, {'apply': false, 'count': 96, 'name': 'kg'},
  {'apply': false, 'count': 63, 'name': 'other'}], 'translatedName': 'Class'},
  {'name': 'subject', 'values': [{'apply': false, 'count': 3, 'name': 'assamese'},
  {'apply': false, 'count': 1, 'name': 'bengali'}, {'apply': false, 'count': 40, 'name': 'english'},
  {'apply': false, 'count': 1, 'name': 'geography'}, {'apply': false, 'count': 176, 'name': 'hindi'},
  {'apply': false, 'count': 1, 'name': 'history'}, {'apply': false, 'count': 8, 'name': 'mathematics'},
  {'apply': false, 'count': 2, 'name': 'odia'}, {'apply': false, 'count': 3, 'name': 'physics'},
  {'apply': false, 'count': 1, 'name': 'urdu'}, {'apply': false, 'count': 7, 'name': 'other'}], 'translatedName': 'Subject'},
  {'name': 'medium', 'values': [{'apply': false, 'count': 1, 'name': 'assamese'}, {'apply': false, 'count': 4, 'name': 'bengali'},
  {'apply': false, 'count': 19, 'name': 'english'}, {'apply': false, 'count': 2, 'name': 'gujarati'},
  {'apply': false, 'count': 45, 'name': 'hindi'}, {'apply': false, 'count': 2, 'name': 'kannada'},
  {'apply': false, 'count': 6, 'name': 'marathi'}, {'apply': false, 'count': 4, 'name': 'odia'},
  {'apply': false, 'count': 3, 'name': 'telugu'}], 'translatedName': 'Medium'},
  {'name': 'contentType', 'values': [], 'translatedName': 'Resource Type'}],
  'facets': ['board', 'gradeLevel', 'subject', 'medium', 'contentType'], 'impliedFilters': [{'name': 'audience', 'values': [{'apply': true,
  'count': 0, 'name': 'instructor'}, {'apply': true, 'count': 0, 'name': 'learner'}]}, {'name': 'status',
  'values': [{'apply': true, 'count': 0, 'name': 'Live'}]}, {'name': 'objectType',
  'values': [{'apply': true, 'count': 0, 'name': 'Content'}]}],
  'limit': 100, 'mode': 'soft', 'offlineSearch': false, 'offset': 0, 'query': 'Hindi', 'searchType': 'FILTER', 'sortCriteria': []},
};
